### PR TITLE
🔀 :: main page 디자인 변경

### LINKED ISSUE #60: Main Page 디자인 변경

### PR DESCRIPTION
**Pull request by MelBIP**
변경된 메인페이지 디자인을 변경하였습니다

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/8bf5bc29-d4c8-40b8-825f-6fbfa4754ed4

### CODE REVIEW

**Comment by MelBIP** [comment]
## Admin MainViewController
#### DarkMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/c7fc40cb-0910-4def-801c-5b8a2fb8709d

#### LightMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/2060e81f-d03c-4f40-a518-8a8bfac18a32


## MainViewController
#### DarkMode

Uploading Simulator Screen Recording - iPhone 15 Pro - 2024-04-20 at 07.24.36.mp4…

#### LightMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/aeccfc19-af32-4c97-b81a-48d0927dfaff

**Comment by saemiee** [comment]
지각자 StackView 안에 View 각각마다 들어가야 할 radius가 적용되지 않은 것 같습니다

**Comment by saemiee** [comment]
다크모드일 때 각 View Background Color가 디자인과 다른 것 같아 확인 부탁드립니다

**Comment by MelBIP** [comment]
# AdminMainViewController
#### DarkMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/ad3213e5-8f2f-4ec3-9e3d-8880fb3f3726


#### LightMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/79dc5559-1509-4a9f-8e48-ed5b86337274

# MainViewController
#### DarkMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/4f1a1928-8269-43bd-bfc4-c6ebcb5fa80f


#### LightMode

https://github.com/team-haribo/GOMS-iOS-V2/assets/104663234/7efb8db6-bc1c-411c-bfa6-e14f5150b2a1

**Comment by MelBIP** [comment]
Simulator Screenshot - iPhone 15 Pro - 2024-04-20 at 14 40 25

Simulator Screenshot - iPhone 15 Pro - 2024-04-20 at 14 37 10

**Pull request merged**
